### ISSUE TITLE
[litcli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by bota87** [lightninglabs/lightning-terminal#527]
I get this error when using litcli
>$ docker exec -it lit litcli a l
>[litcli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"

**System information**
I run terminal and lnd on different containers on the same server.
I can access the web ui and manage my node from that so I suppose that the configuration is fine.
```
docker-compose.yml
  lit:
    restart: unless-stopped
    expose:
      - 8443
    volumes:
      - /data/lit:/root/.lit
      - /data/lnd/data/chain/bitcoin/mainnet/admin.macaroon:/root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon:ro
      - /data/lnd/tls.cert:/root/.lnd/tls.cert:ro
    depends_on:
      - lnd
    container_name: lit
    image: lightninglabs/lightning-terminal:v0.8.6-alpha

  lnd:
    restart: unless-stopped
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - /data/lnd:/root/.lnd
    container_name: lnd
    image: lightninglabs/lnd:v0.15.4-beta
```
```
lit.conf
# Application Options
httpslisten=0.0.0.0:8443
uipassword=******
lnd-mode=remote

# Remote lnd options
remote.lnd.rpcserver=lnd:10009
```
